"""
PPTAgent PPTX 生成器

使用 Python + python-pptx 将解析后的 HTML 元素转换为可编辑的 PPTX 文件。

技术方案（参考智谱清言）：
1. 使用 html_parser 解析 HTML，提取元素位置和样式
2. 使用 python-pptx 创建 PPTX 文件
3. 将每个元素转换为对应的 PPTX 元素（文本框、形状、图片）

优点：
- 文本可编辑
- 形状可编辑
- 保持原始布局

更新日志：
- 2026-01-17: 重构，使用 HTML 解析 + python-pptx 生成可编辑 PPTX
- 2026-01-17: 修复文本框尺寸问题，增加宽度余量，设置自动调整
"""

import os
import io
import uuid
import logging
import asyncio
import tempfile
import shutil
import requests
from typing import List, Tuple, Optional, Dict, Any
from pathlib import Path
from datetime import datetime
from dataclasses import asdict

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR, MSO_AUTO_SIZE
from pptx.enum.shapes import MSO_SHAPE
from pptx.oxml.ns import nsmap

from services.html_parser import parse_html, SlideData, SlideElement, Position, TextStyle, ShapeStyle

logger = logging.getLogger(__name__)


class PptxGenerator:
    """
    PPTX 生成器
    
    将 HTML 幻灯片转换为可编辑的 PPTX 文件。
    """
    
    # 幻灯片尺寸（16:9）
    SLIDE_WIDTH_INCH = 10
    SLIDE_HEIGHT_INCH = 5.625
    
    # 文本框宽度余量（解决字体渲染差异导致的文字截断）
    TEXT_WIDTH_MARGIN = 1.15  # 增加 15% 余量
    
    # 最小文本框尺寸
    MIN_TEXTBOX_WIDTH = 0.5  # 英寸
    MIN_TEXTBOX_HEIGHT = 0.3  # 英寸
    
    def __init__(self):
        self.temp_dir: Optional[Path] = None
        self.image_cache: Dict[str, str] = {}  # URL -> 本地路径
        
    async def generate(
        self,
        slides_html: List[str],
        output_path: str,
        title: str = "Presentation"
    ) -> str:
        """
        生成 PPTX 文件
        
        Args:
            slides_html: HTML 幻灯片列表
            output_path: 输出文件路径
            title: 演示文稿标题
            
        Returns:
            生成的 PPTX 文件路径
        """
        # 创建临时目录
        self.temp_dir = Path(tempfile.mkdtemp(prefix="pptx_gen_"))
        self.image_cache = {}
        
        try:
            # 创建演示文稿
            prs = Presentation()
            prs.slide_width = Inches(self.SLIDE_WIDTH_INCH)
            prs.slide_height = Inches(self.SLIDE_HEIGHT_INCH)
            
            # 获取空白布局
            blank_layout = prs.slide_layouts[6]  # 空白布局
            
            # 处理每张幻灯片
            for i, html in enumerate(slides_html):
                logger.info(f"处理幻灯片 {i+1}/{len(slides_html)}...")
                
                try:
                    # 解析 HTML
                    slide_data = await parse_html(html)
                    
                    # 创建幻灯片
                    slide = prs.slides.add_slide(blank_layout)
                    
                    # 设置背景
                    self._set_background(slide, slide_data.background)
                    
                    # 添加元素（先添加形状，再添加文本，最后添加图片）
                    shapes = [e for e in slide_data.elements if e.type == 'shape']
                    texts = [e for e in slide_data.elements if e.type == 'text']
                    images = [e for e in slide_data.elements if e.type == 'image']
                    
                    for element in shapes:
                        await self._add_element(slide, element)
                    for element in texts:
                        await self._add_element(slide, element)
                    for element in images:
                        await self._add_element(slide, element)
                    
                    logger.info(f"幻灯片 {i+1} 完成，包含 {len(slide_data.elements)} 个元素")
                    
                except Exception as e:
                    logger.error(f"处理幻灯片 {i+1} 失败: {e}")
                    import traceback
                    traceback.print_exc()
                    # 创建一个空白幻灯片作为占位
                    slide = prs.slides.add_slide(blank_layout)
                    # 添加错误提示
                    self._add_error_placeholder(slide, i+1, str(e))
            
            # 设置文档属性
            prs.core_properties.title = title
            prs.core_properties.author = "PPTAgent"
            prs.core_properties.comments = "Generated by PPTAgent"
            
            # 保存文件
            prs.save(output_path)
            logger.info(f"PPTX 生成成功: {output_path}")
            
            return output_path
            
        finally:
            # 清理临时目录
            if self.temp_dir and self.temp_dir.exists():
                shutil.rmtree(self.temp_dir)
                logger.info(f"临时目录已清理: {self.temp_dir}")
    
    def _set_background(self, slide, background: Dict[str, Any]) -> None:
        """设置幻灯片背景"""
        try:
            if background.get('type') == 'color':
                color_hex = background.get('value', '#FFFFFF')
                rgb = self._hex_to_rgb(color_hex)
                if rgb:
                    slide.background.fill.solid()
                    slide.background.fill.fore_color.rgb = rgb
        except Exception as e:
            logger.warning(f"设置背景失败: {e}")
    
    async def _add_element(self, slide, element: SlideElement) -> None:
        """添加元素到幻灯片"""
        try:
            if element.type == 'text':
                self._add_text_element(slide, element)
            elif element.type == 'shape':
                self._add_shape_element(slide, element)
            elif element.type == 'image':
                await self._add_image_element(slide, element)
        except Exception as e:
            logger.warning(f"添加元素失败: {e}")
    
    def _add_text_element(self, slide, element: SlideElement) -> None:
        """添加文本元素"""
        pos = element.position
        style = element.style
        content = element.content or ""
        
        if not content.strip():
            return
        
        # 计算文本框尺寸，增加余量避免文字截断
        width = max(pos.w * self.TEXT_WIDTH_MARGIN, self.MIN_TEXTBOX_WIDTH)
        height = max(pos.h * 1.1, self.MIN_TEXTBOX_HEIGHT)  # 高度也增加 10% 余量
        
        # 确保文本框不超出幻灯片边界
        x = pos.x
        y = pos.y
        
        # 如果文本框超出右边界，调整位置或宽度
        if x + width > self.SLIDE_WIDTH_INCH:
            # 优先调整宽度
            available_width = self.SLIDE_WIDTH_INCH - x - 0.1  # 留 0.1 英寸边距
            if available_width > self.MIN_TEXTBOX_WIDTH:
                width = available_width
            else:
                # 如果宽度不够，调整 x 位置
                x = max(0.1, self.SLIDE_WIDTH_INCH - width - 0.1)
        
        # 如果文本框超出下边界，调整位置或高度
        if y + height > self.SLIDE_HEIGHT_INCH:
            available_height = self.SLIDE_HEIGHT_INCH - y - 0.1
            if available_height > self.MIN_TEXTBOX_HEIGHT:
                height = available_height
            else:
                y = max(0.1, self.SLIDE_HEIGHT_INCH - height - 0.1)
        
        # 创建文本框
        textbox = slide.shapes.add_textbox(
            Inches(x),
            Inches(y),
            Inches(width),
            Inches(height)
        )
        
        # 设置文本框属性
        tf = textbox.text_frame
        tf.word_wrap = True  # 启用自动换行
        
        # 设置自动调整大小 - 让文本框根据内容自动调整
        # 注意：MSO_AUTO_SIZE.SHAPE_TO_FIT_TEXT 会让形状适应文本
        # MSO_AUTO_SIZE.TEXT_TO_FIT_SHAPE 会让文本缩小以适应形状
        # MSO_AUTO_SIZE.NONE 不自动调整
        try:
            tf.auto_size = MSO_AUTO_SIZE.SHAPE_TO_FIT_TEXT
        except Exception:
            pass  # 某些情况下可能不支持
        
        # 设置边距为 0，让文本更紧凑
        tf.margin_left = Inches(0.05)
        tf.margin_right = Inches(0.05)
        tf.margin_top = Inches(0.02)
        tf.margin_bottom = Inches(0.02)
        
        # 设置垂直对齐
        if hasattr(style, 'valign'):
            if style.valign == 'middle':
                tf.anchor = MSO_ANCHOR.MIDDLE
            elif style.valign == 'bottom':
                tf.anchor = MSO_ANCHOR.BOTTOM
            else:
                tf.anchor = MSO_ANCHOR.TOP
        
        # 添加段落
        p = tf.paragraphs[0]
        
        # 设置段落样式
        if hasattr(style, 'align'):
            if style.align == 'center':
                p.alignment = PP_ALIGN.CENTER
            elif style.align == 'right':
                p.alignment = PP_ALIGN.RIGHT
            else:
                p.alignment = PP_ALIGN.LEFT
        
        # 设置行间距
        if hasattr(style, 'line_spacing') and style.line_spacing:
            try:
                p.line_spacing = style.line_spacing
            except Exception:
                pass
        
        # 添加文本运行
        run = p.add_run()
        run.text = content
        
        # 设置字体样式
        if hasattr(style, 'font_size') and style.font_size:
            run.font.size = Pt(style.font_size)
        
        if hasattr(style, 'font_family') and style.font_family:
            # 处理字体名称，移除引号和多余空格
            font_name = style.font_family.strip().strip('"').strip("'")
            # 如果是通用字体族，使用默认字体
            if font_name.lower() in ['sans-serif', 'serif', 'monospace']:
                font_name = 'Microsoft YaHei'  # 使用微软雅黑作为默认中文字体
            run.font.name = font_name
        else:
            run.font.name = 'Microsoft YaHei'  # 默认使用微软雅黑
        
        if hasattr(style, 'color') and style.color:
            rgb = self._hex_to_rgb(style.color)
            if rgb:
                run.font.color.rgb = rgb
        
        if hasattr(style, 'bold'):
            run.font.bold = style.bold
        
        if hasattr(style, 'italic'):
            run.font.italic = style.italic
        
        if hasattr(style, 'underline'):
            run.font.underline = style.underline
    
    def _add_shape_element(self, slide, element: SlideElement) -> None:
        """添加形状元素"""
        pos = element.position
        style = element.style
        
        # 确保形状不超出幻灯片边界
        x = min(pos.x, self.SLIDE_WIDTH_INCH - 0.1)
        y = min(pos.y, self.SLIDE_HEIGHT_INCH - 0.1)
        w = min(pos.w, self.SLIDE_WIDTH_INCH - x)
        h = min(pos.h, self.SLIDE_HEIGHT_INCH - y)
        
        # 确定形状类型
        if hasattr(style, 'border_radius') and style.border_radius > 0:
            shape_type = MSO_SHAPE.ROUNDED_RECTANGLE
        else:
            shape_type = MSO_SHAPE.RECTANGLE
        
        # 创建形状
        shape = slide.shapes.add_shape(
            shape_type,
            Inches(x),
            Inches(y),
            Inches(w),
            Inches(h)
        )
        
        # 设置填充颜色
        if hasattr(style, 'fill_color') and style.fill_color:
            rgb = self._hex_to_rgb(style.fill_color)
            if rgb:
                shape.fill.solid()
                shape.fill.fore_color.rgb = rgb
        else:
            shape.fill.background()  # 透明填充
        
        # 设置边框
        if hasattr(style, 'border_color') and style.border_color and hasattr(style, 'border_width') and style.border_width > 0:
            rgb = self._hex_to_rgb(style.border_color)
            if rgb:
                shape.line.color.rgb = rgb
                shape.line.width = Pt(style.border_width)
        else:
            shape.line.fill.background()  # 无边框
    
    async def _add_image_element(self, slide, element: SlideElement) -> None:
        """添加图片元素"""
        pos = element.position
        src = element.src
        
        if not src:
            return
        
        try:
            # 下载图片
            image_path = await self._download_image(src)
            
            if image_path and os.path.exists(image_path):
                # 确保图片不超出幻灯片边界
                x = min(pos.x, self.SLIDE_WIDTH_INCH - 0.1)
                y = min(pos.y, self.SLIDE_HEIGHT_INCH - 0.1)
                w = min(pos.w, self.SLIDE_WIDTH_INCH - x)
                h = min(pos.h, self.SLIDE_HEIGHT_INCH - y)
                
                # 添加图片
                slide.shapes.add_picture(
                    image_path,
                    Inches(x),
                    Inches(y),
                    width=Inches(w),
                    height=Inches(h)
                )
        except Exception as e:
            logger.warning(f"添加图片失败: {src}, 错误: {e}")
    
    async def _download_image(self, url: str) -> Optional[str]:
        """下载图片到临时目录"""
        # 检查缓存
        if url in self.image_cache:
            return self.image_cache[url]
        
        try:
            # 处理 data URL
            if url.startswith('data:'):
                return self._save_data_url(url)
            
            # 下载网络图片
            response = requests.get(url, timeout=10, stream=True)
            response.raise_for_status()
            
            # 确定文件扩展名
            content_type = response.headers.get('content-type', '')
            if 'png' in content_type:
                ext = '.png'
            elif 'gif' in content_type:
                ext = '.gif'
            elif 'webp' in content_type:
                ext = '.webp'
            else:
                ext = '.jpg'
            
            # 保存到临时目录
            filename = f"image_{uuid.uuid4().hex[:8]}{ext}"
            filepath = self.temp_dir / filename
            
            with open(filepath, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)
            
            self.image_cache[url] = str(filepath)
            return str(filepath)
            
        except Exception as e:
            logger.warning(f"下载图片失败: {url}, 错误: {e}")
            return None
    
    def _save_data_url(self, data_url: str) -> Optional[str]:
        """保存 data URL 图片"""
        try:
            import base64
            
            # 解析 data URL
            header, data = data_url.split(',', 1)
            
            # 确定文件扩展名
            if 'png' in header:
                ext = '.png'
            elif 'gif' in header:
                ext = '.gif'
            elif 'webp' in header:
                ext = '.webp'
            else:
                ext = '.jpg'
            
            # 解码并保存
            image_data = base64.b64decode(data)
            filename = f"image_{uuid.uuid4().hex[:8]}{ext}"
            filepath = self.temp_dir / filename
            
            with open(filepath, 'wb') as f:
                f.write(image_data)
            
            return str(filepath)
            
        except Exception as e:
            logger.warning(f"保存 data URL 图片失败: {e}")
            return None
    
    def _add_error_placeholder(self, slide, slide_num: int, error: str) -> None:
        """添加错误占位符"""
        textbox = slide.shapes.add_textbox(
            Inches(1),
            Inches(2),
            Inches(8),
            Inches(2)
        )
        tf = textbox.text_frame
        p = tf.paragraphs[0]
        p.text = f"幻灯片 {slide_num} 生成失败\n{error}"
        p.alignment = PP_ALIGN.CENTER
        run = p.runs[0]
        run.font.size = Pt(24)
        run.font.color.rgb = RGBColor(255, 0, 0)
    
    def _hex_to_rgb(self, hex_color: str) -> Optional[RGBColor]:
        """将十六进制颜色转换为 RGBColor"""
        if not hex_color:
            return None
        
        try:
            # 移除 # 前缀
            hex_color = hex_color.lstrip('#')
            
            # 处理简写形式 (如 #FFF)
            if len(hex_color) == 3:
                hex_color = ''.join([c*2 for c in hex_color])
            
            if len(hex_color) != 6:
                return None
            
            r = int(hex_color[0:2], 16)
            g = int(hex_color[2:4], 16)
            b = int(hex_color[4:6], 16)
            
            return RGBColor(r, g, b)
            
        except Exception:
            return None


# 单例实例
pptx_generator = PptxGenerator()


async def generate_pptx(
    slides_html: List[str],
    output_path: str,
    title: str = "Presentation"
) -> str:
    """
    生成 PPTX 文件的便捷函数
    
    Args:
        slides_html: HTML 幻灯片列表
        output_path: 输出文件路径
        title: 演示文稿标题
        
    Returns:
        生成的 PPTX 文件路径
    """
    return await pptx_generator.generate(slides_html, output_path, title)
